branch-defaults:
  master:
    environment: subnet-75db9503
    group_suffix: null
global:
  application_name: radio
  branch: null
  default_ec2_keyname: MyKeyPair
  default_platform: PHP 7.0
  default_region: ap-northeast-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
